// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwkgnukqwpamjaurigmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3a2dudWtxd3BhbWphdXJpZ21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5MTgxNTYsImV4cCI6MjA1MzQ5NDE1Nn0.Om5jXc1zk2pRUOnNPX4pSVyLihE6dTC3N-uN673nAXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);